[project]
name = "HTB"
version = "0.1.0"
description = "HTB writeups and tools"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13.5",
    "asyncssh>=2.22.0",
    "bcrypt>=5.0.0",
    "beautifulsoup4>=4.14.3",
    "bloodhound>=1.9.0",
    "bloodyad>=2.5.4",
    "boto3>=1.42.84",
    "boto3-stubs>=1.42.84",
    "certipy-ad>=4.8.2",
    "coercer>=2.4.3",
    "flask-unsign>=1.2.1",
    "fonttools==4.60.1",
    "git-dumper>=1.0.9",
    "impacket>=0.10.0",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "nbconvert>=7.17.0",
    "netifaces2>=0.0.22",
    "psutil>=7.2.2",
    "pyaescrypt>=6.1.1",
    "pypykatz>=0.6.13",
    "rich>=14.3.4",
    "sh>=2.2.2",
    "tqdm>=4.67.3",
    "yarl>=1.23.0",
]
